name: aquawatch
version: '1.0.0'
config-version: 2
profile: aquawatch
model-paths: [models]
seed-paths: [seeds]
test-paths: [tests]
macro-paths: [macros]
clean-targets: [target, dbt_packages]
models:
  aquawatch:
    staging:
      +materialized: view
    marts:
      +materialized: table
seeds:
  aquawatch:
    +quote_columns: false
